--$Id:$--
--
DROP INDEX IF EXISTS IDX_WF_PROC_UNIQ_CODE^
ALTER TABLE WF_PROC DROP CONSTRAINT IF EXISTS WF_PROC_UNIQ_CODE^
CREATE UNIQUE INDEX IDX_WF_PROC_UNIQ_CODE ON WF_PROC (CODE) WHERE DELETE_TS IS NULL^